homebrew_taps:
  - heroku/brew
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - jgarber623/extras
  - name: jgarber623/private
    url: https://${HOMEBREW_GITHUB_TOKEN}:x-oauth-basic@github.com/jgarber623/homebrew-private

dotfiles_repo: https://github.com/jgarber623/dotfiles
dotfiles_repo_version: main
dotfiles_repo_local_destination: ~/.dotfiles

dotfiles_files:
  - .atom/config.cson
  - .atom/init.coffee
  - .atom/keymap.cson
  - .atom/packages.txt
  - .atom/snippets.cson
  - .atom/styles.less
  - .bundle/config
  - .oh-my-zsh/custom/functions.zsh
  - .oh-my-zsh/custom/homebrew.zsh
  - .oh-my-zsh/custom/rbenv.zsh
  - .oh-my-zsh/custom/themes/jgarber.zsh-theme
  - .curlrc
  - .gemrc
  - .gitattributes
  - .gitconfig
  - .gitignore
  - .irbrc
  - .npmrc
  - .pryrc
  - .tmux.conf
  - .wgetrc
  - .zshrc

omz_user:
  name: "{{ ansible_user_id }}"
  group: "{{ ansible_user_gid }}"
omz_zshrc_create: false
