configure_dotfiles: true

configure_atom: true
configure_ssh: true
configure_terminal: true

dotfiles_repo: https://github.com/jgarber623/dotfiles
dotfiles_repo_version: main
dotfiles_repo_local_destination: ~/.dotfiles

dotfiles_files:
  - .atom/config.cson
  - .atom/init.coffee
  - .atom/keymap.cson
  - .atom/packages.txt
  - .atom/snippets.cson
  - .atom/styles.less
  - .bundle/config
  - .config/bat/config
  - .oh-my-zsh/custom/aliases.zsh
  - .oh-my-zsh/custom/functions.zsh
  - .oh-my-zsh/custom/themes/jgarber.zsh-theme
  - .curlrc
  - .gemrc
  - .gitattributes
  - .gitconfig
  - .gitignore
  - .gnupg/gpg-agent.conf
  - .irbrc
  - .npmrc
  - .pryrc
  - .rbenv/default-gems
  - .ssh/config
  - .tmux.conf
  - .wgetrc
  - .zshrc

homebrew_taps:
  - heroku/brew
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - jgarber623/extras
  - name: jgarber623/private
    url: https://${HOMEBREW_GITHUB_TOKEN}:x-oauth-basic@github.com/jgarber623/homebrew-private

homebrew_installed_packages:
  - gh
  - git
  - gnupg
  - mas
  - nano
  - node
  - nvm
  - openssh
  - pygments
  - rbenv
  - rbenv-aliases
  - rbenv-default-gems
  - jgarber623/extras/rbenv-each
  - jgarber623/extras/rbenv-env
  - jgarber623/extras/rbenv-gem-update
  - ruby-build
  - zsh

homebrew_cask_apps:
  - 1password
  - atom

mas_installed_apps: []

mas_upgrade_all_apps: false

omz_user:
  name: "{{ ansible_user_id }}"
  group: "{{ ansible_user_gid }}"

omz_zshrc_create: false

ssh_agent_bin_path: "{{ (ansible_machine == 'arm64') | ternary('/opt/homebrew', '/usr/local') }}/bin/ssh-agent"
ssh_agent_launchd_service: org.homebrew.openssh.ssh-agent
ssh_agent_socket_path: ~/.ssh/agent
