configure_dotfiles: true

dotfiles_repo: https://github.com/jgarber623/dotfiles
dotfiles_repo_version: main
dotfiles_repo_local_destination: ~/.dotfiles

dotfiles_files:
  - .atom/config.cson
  - .atom/init.coffee
  - .atom/keymap.cson
  - .atom/packages.txt
  - .atom/snippets.cson
  - .atom/styles.less
  - .bundle/config
  - .oh-my-zsh/custom/aliases.zsh
  - .oh-my-zsh/custom/functions.zsh
  - .oh-my-zsh/custom/homebrew.zsh
  - .oh-my-zsh/custom/themes/jgarber.zsh-theme
  - .curlrc
  - .gemrc
  - .gitattributes
  - .gitconfig
  - .gitignore
  - .irbrc
  - .npmrc
  - .pryrc
  - .rbenv/default-gems
  - .tmux.conf
  - .wgetrc
  - .zshrc

homebrew_taps:
  - heroku/brew
  - homebrew/cask-drivers
  - homebrew/cask-fonts
  - jgarber623/extras
  - name: jgarber623/private
    url: https://${HOMEBREW_GITHUB_TOKEN}:x-oauth-basic@github.com/jgarber623/homebrew-private

homebrew_installed_packages:
  - base64
  - circleci
  - fd
  - fx
  - gh
  - git
  - gnupg
  - grpcurl
  - heroku
  - hr
  - htop
  - jq
  - lame
  - lynx
  - mas
  - nano
  - netlify-cli
  - nmap
  - node
  - nvm
  - openssh
  - pidof
  - pygments
  - rbenv
  - rbenv-aliases
  - rbenv-default-gems
  - jgarber623/extras/rbenv-each
  - jgarber623/extras/rbenv-env
  - jgarber623/extras/rbenv-gem-update
  - rbenv-use
  - ruby-build
  - screen
  - svgo
  - tmux
  - trash
  - tree
  - xh
  - wget
  - wrk
  - yarn
  - ykman
  - youtube-dl
  - zsh

homebrew_cask_apps:
  - 1password
  - alfred
  - appcleaner
  - atom
  - bartender
  - devdocs
  - docker
  - encryptme
  - firefox
  - fission
  - font-b612
  - jgarber623/extras/font-bodoni
  - jgarber623/private/font-boss
  - font-cascadia-code
  - font-ia-writer-duo
  - font-ia-writer-duospace
  - font-ia-writer-mono
  - font-ia-writer-quattro
  - font-ibm-plex
  - jgarber623/extras/font-jost
  - font-lato
  - jgarber623/private/font-museo
  - jgarber623/private/font-museo-sans
  - jgarber623/private/font-museo-slab
  - font-national-park
  - font-new-york
  - jgarber623/private/font-operator-mono
  - jgarber623/private/font-operator-pro
  - font-optician-sans
  - font-public-sans
  - font-sf-compact
  - font-sf-mono
  - font-sf-pro
  - jgarber623/extras/font-techna-sans
  - font-vollkorn
  - font-work-sans
  - github
  - google-chrome
  - google-cloud-sdk
  - handbrake
  - imagealpha
  - imageoptim
  - insomnia
  - little-snitch
  - menuwhere
  - micro-snitch
  - monity-helper
  - onyx
  - proxyman
  - psequel
  - rocket
  - screens
  - signal
  - sketch
  - transmission
  - transmit
  - vlc
  - vmware-fusion
  - yubico-yubikey-manager

mas_installed_apps:
  - name: 1Blocker
    id: 1365531024
  - name: Airmail
    id: 918858936
  - name: Bear
    id: 1091189122
  - name: Cardhop
    id: 1290358394
  - name: Clear
    id: 504544917
  - name: Contrast
    id: 1254981365
  - name: Day One
    id: 1055511498
  - name: Deliveries
    id: 924726344
  - name: Fantastical
    id: 975937182
  - name: GarageBand
    id: 682658836
  - name: GIF Brewery 3
    id: 1081413713
  - name: GoodNotes
    id: 1444383602
  - name: Icon Slate
    id: 439697913
  - name: iMovie
    id: 408981434
  - name: Instapaper
    id: 288545208
  - name: Instapaper Save
    id: 1481302432
  - name: JSONPeep
    id: 1458969831
  - name: Keynote
    id: 409183694
  - name: Keypad
    id: 928906884
  - name: Mactracker
    id: 430255202
  - name: Marked 2
    id: 890031187
  - name: Monity
    id: 915542151
  - name: Moom
    id: 419330170
  - name: Name Mangler
    id: 603637384
  - name: Numbers
    id: 409203825
  - name: Pages
    id: 409201541
  - name: Paprika Recipe Manager 3
    id: 1303222628
  - name: Patterns
    id: 429449079
  - name: Pixelmator
    id: 407963104
  - name: Pixelmator Pro
    id: 1289583905
  - name: Playgrounds
    id: 1496833156
  - name: Reeder
    id: 1529448980
  - name: Slack
    id: 803453959
  - name: StopTheMadness
    id: 1376402589
  - name: The Unarchiver
    id: 425424353
  - name: Tweetbot
    id: 1384080005

omz_user:
  name: "{{ ansible_user_id }}"
  group: "{{ ansible_user_gid }}"

omz_zshrc_create: false
