- hosts: localhost
  environment:
    HOMEBREW_GITHUB_TOKEN: "{{ homebrew_github_token }}"
  vars_files:
    - config.default.yml
  vars_prompt:
    - name: homebrew_github_token
      prompt: "Enter a value for HOMEBREW_GITHUB_TOKEN:"
      confirm: true
  pre_tasks:
    - name: Include additional custom configuration
      include_vars: "{{ item }}"
      with_fileglob:
        - config.yml
      tags: ["always"]
    - name: Ensure ~/.brewrc file exports HOMEBREW_GITHUB_TOKEN
      lineinfile:
        path: "{{ lookup('env', 'HOME') }}/.brewrc"
        regexp: "^export HOMEBREW_GITHUB_TOKEN="
        line: export HOMEBREW_GITHUB_TOKEN={{ homebrew_github_token }}
        create: true
      tags: ["homebrew"]
  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ["homebrew"]
    - role: geerlingguy.mac.mas
      when: mas_installed_apps
    - role: ctorgalson.oh-my-zsh
      when: configure_dotfiles
      tags: ["dotfiles"]
      become: true
    - role: jgarber623.dotfiles
      when: configure_dotfiles
      tags: ["dotfiles"]
  tasks:
    - import_tasks: tasks/ruby.yml
      tags: ["ruby"]
    - import_tasks: tasks/node.yml
      tags: ["node"]
  post_tasks:
