- hosts: localhost
  environment:
    HOMEBREW_GITHUB_TOKEN: "{{ homebrew_github_token }}"
  vars_files:
    - config.default.yml
  vars_prompt:
    - name: homebrew_github_token
      prompt: "Enter a value for HOMEBREW_GITHUB_TOKEN"
  pre_tasks:
    - name: Include additional custom configuration
      include_vars: "{{ item }}"
      with_fileglob:
        - config.yml
      tags: ["always"]
    - name: Ensure ~/.env file exports HOMEBREW_GITHUB_TOKEN
      lineinfile:
        path: "{{ lookup('env', 'HOME') }}/.env"
        regexp: "^export HOMEBREW_GITHUB_TOKEN="
        line: export HOMEBREW_GITHUB_TOKEN={{ homebrew_github_token }}
        create: true
      tags: ["homebrew"]
  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ["homebrew"]
    - role: ctorgalson.oh-my-zsh
      when: configure_dotfiles
      tags: ["dotfiles"]
    - role: jgarber623.dotfiles
      when: configure_dotfiles
      tags: ["dotfiles"]
  tasks:
    - import_tasks: tasks/atom.yml
      when: configure_atom
      tags: ["atom"]
    - import_tasks: tasks/ssh.yml
      when: configure_ssh
      tags: ["ssh"]
    - import_tasks: tasks/terminal.yml
      when: configure_terminal
      tags: ["terminal"]
    - import_tasks: tasks/mas.yml
      when: mas_installed_apps
      tags: ["mas"]
  post_tasks:
