roles:
  - name: ctorgalson.oh-my-zsh
  - name: elliotweiser.osx-command-line-tools
  - name: jgarber623.dotfiles
    src: https://github.com/jgarber623/ansible-role-dotfiles

collections:
  - name: geerlingguy.mac
