- name: Ensure mas-cli is installed.
  community.general.homebrew:
    name: mas

- name: Install configured Mac App Store apps.
  community.general.mas:
    id: "{{ item }}"
  with_items: "{{ mas_installed_apps }}"

- name: Upgrade all installed Mac App Store apps.
  community.general.mas:
    upgrade_all: true
  when: mas_upgrade_all_apps
