- name: Check if nvm is installed.
  stat:
    path: "{{ (ansible_machine == 'arm64') | ternary('/opt/homebrew', '/usr/local') }}/opt/nvm/nvm.sh"
  register: nvm_script

- name: Source nvm.
  command: source {{ nvm_script.stat.path }}
  when: nvm_script.stat.exists

- name: Set nvm's default Node.js version.
  command: nvm alias default system
  args:
    creates: "{{ lookup('env', 'NVM_DIR') }}/alias/default"
  when: nvm_script.stat.exists
