- name: Check if rbenv is installed.
  stat:
    path: "{{ (ansible_machine == 'arm64') | ternary('/opt/homebrew', '/usr/local') }}/bin/rbenv"
  register: rbenv_binary

- name: Set rbenv's global Ruby version.
  command: "{{ rbenv_binary.stats.path }} global system"
  args:
    creates: "{{ lookup('env', 'HOME') }}/.rbenv/version"
  when: rbenv_binary.stat.exists
