- name: Set rbenv's global Ruby version.
  command: $(brew --prefix)/bin/rbenv global system
  args:
    creates: "{{ lookup('env', 'HOME') }}/.rbenv/version"

- name: Install default gems to system Ruby.
  command: gem install {{ item }}
  with_lines: cat {{ lookup('env', 'HOME') }}/.rbenv/default-gems
