- name: Ensure openssh is installed.
  community.general.homebrew:
    name: openssh

- name: Ensure ~/.ssh directory exists.
  file:
    path: ~/.ssh
    state: directory
    mode: u=rwX,g=rX,o=rX

- name: Disable macOS' default ssh-agent for this user.
  community.general.launchd:
    name: com.openssh.ssh-agent
    state: unloaded
    enabled: false

- name: Ensure ~/Library/LaunchAgents directory exists.
  file:
    path: ~/Library/LaunchAgents
    state: directory
    mode: u=rwX,g=rX,o=rX

- name: Copy custom launchd service for Homebrew's ssh-agent.
  template:
    src: ssh-agent.plist.j2
    dest: ~/Library/LaunchAgents/{{ ssh_agent_launchd_service }}.plist
    mode: u=rw,g=r,o=r

- name: Enable Homebrew's ssh-agent for this user.
  community.general.launchd:
    name: "{{ ssh_agent_launchd_service }}"
    enabled: true
