- name: Get current Terminal profile name.
  community.general.osx_defaults:
    domain: com.apple.terminal
    key: "Default Window Settings"
    state: list
  register: terminal_profile

- name: Import custom Terminal profile.
  command: open {{ role_path }}/files/terminal/profile.terminal
  changed_when: false
  when: "'SpaceGray Eighties Dull' not in terminal_theme.stdout"

- name: Set custom Terminal profile as default.
  community.general.osx_defaults:
    domain: com.apple.terminal
    key: "{{ item }}"
    value: "SpaceGray Eighties Dull"
  with_items:
    - "Default Window Settings"
    - "Startup Window Settings"
  when: "'SpaceGray Eighties Dull' not in terminal_theme.stdout"
