- name: Get current Terminal profile name.
  community.general.osx_defaults:
    domain: com.apple.terminal
    key: "Default Window Settings"
    state: list
  register: terminal_profile

- name: Import custom Terminal profile.
  command: open {{ playbook_dir }}/files/terminal/SpaceGray\ Eighties\ Dull.terminal
  changed_when: false
  when: terminal_profile != "SpaceGray Eighties Dull"

- name: Set custom Terminal profile as default.
  community.general.osx_defaults:
    domain: com.apple.terminal
    key: "{{ item }}"
    value: "SpaceGray Eighties Dull"
  with_items:
    - "Default Window Settings"
    - "Startup Window Settings"
  when: terminal_profile != "SpaceGray Eighties Dull"
