name: CI

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          path: ${{ env.pythonLocation }}
          key: ${{ runner.os }}-${{ env.pythonLocation }}-v1
      - run: pip3 install ansible ansible-lint yamllint
      - run: yamllint --format parsable .
      - run: ansible-lint
  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-11
    steps:
      - uses: actions/checkout@v2
      - name: Uninstall GitHub Actions' pre-installed Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
      - name: Run bootstrap script
        run: bin/bootstrap
      - run: ansible --version
