name: CI

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip3 install ansible ansible-lint yamllint
      - run: yamllint --format parsable .
      - run: ansible-lint
